### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by DanielDeychakiwsky** [gamechanger/mongothon#54]
I'm importing `create_model`: 

`from mongothon import create_model`

I get: 

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "src/__main__.py", line 3, in <module>
    from database.mongodb.Collection import Collection
  File "src/database/mongodb/Collection.py", line 1, in <module>
    from mongothon import create_model
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/mongothon/__init__.py", line 3, in <module>
    from document import Document
ImportError: No module named 'document'
```

Any ideas?

**Comment by inlinestyle** [comment]
I don't think `mongothon` has python 3 support (it looks like an issue with relative import)

**Comment by thieman** [comment]
Sorry for the confusion. Opened https://github.com/gamechanger/mongothon/pull/55
